//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SulpHurEntitiesForReport : DbContext
    {
        public SulpHurEntitiesForReport()
            : base("name=SulpHurEntitiesForReport")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssemblyInfo> AssemblyInfoes { get; set; }
        public virtual DbSet<AssemblyLink> AssemblyLinks { get; set; }
        public virtual DbSet<bug_surface> bug_surface { get; set; }
        public virtual DbSet<BugLink> BugLinks { get; set; }
        public virtual DbSet<bug> bugs { get; set; }
        public virtual DbSet<BuildInfo> BuildInfoes { get; set; }
        public virtual DbSet<BuildType> BuildTypes { get; set; }
        public virtual DbSet<BuildVersionMap> BuildVersionMaps { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DeletedContent> DeletedContents { get; set; }
        public virtual DbSet<DeletedContentsTemp> DeletedContentsTemps { get; set; }
        public virtual DbSet<FilterSpellCheck_abnormalButNoImpact> FilterSpellCheck_abnormalButNoImpact { get; set; }
        public virtual DbSet<FilterSpellCheck_exceptionPageTitle> FilterSpellCheck_exceptionPageTitle { get; set; }
        public virtual DbSet<FilterSpellCheck_excludeTextDetectPageTitle> FilterSpellCheck_excludeTextDetectPageTitle { get; set; }
        public virtual DbSet<FilterSpellCheck_nonEnglishButtonName> FilterSpellCheck_nonEnglishButtonName { get; set; }
        public virtual DbSet<FilterSpellCheck_normalPunctuation> FilterSpellCheck_normalPunctuation { get; set; }
        public virtual DbSet<FilterSpellCheck_pageExceptionType> FilterSpellCheck_pageExceptionType { get; set; }
        public virtual DbSet<FilterSpellCheck_properNoun> FilterSpellCheck_properNoun { get; set; }
        public virtual DbSet<FilterSpellCheck_regexString> FilterSpellCheck_regexString { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LCX_Assemblies> LCX_Assemblies { get; set; }
        public virtual DbSet<LCX_AssociationAssembly> LCX_AssociationAssembly { get; set; }
        public virtual DbSet<LCX_Cache> LCX_Cache { get; set; }
        public virtual DbSet<LCX_CacheLanguage> LCX_CacheLanguage { get; set; }
        public virtual DbSet<LCX_Details> LCX_Details { get; set; }
        public virtual DbSet<LCX_Employers> LCX_Employers { get; set; }
        public virtual DbSet<LCX_Features> LCX_Features { get; set; }
        public virtual DbSet<LCX_FilteredStrs> LCX_FilteredStrs { get; set; }
        public virtual DbSet<LCX_MainReport> LCX_MainReport { get; set; }
        public virtual DbSet<LCX_Status> LCX_Status { get; set; }
        public virtual DbSet<LCX_StringBuilds> LCX_StringBuilds { get; set; }
        public virtual DbSet<LCX_StringDetails> LCX_StringDetails { get; set; }
        public virtual DbSet<LogException> LogExceptions { get; set; }
        public virtual DbSet<NonEnglishWordsButEnglishLetter> NonEnglishWordsButEnglishLetters { get; set; }
        public virtual DbSet<OverlapRuleFilter> OverlapRuleFilters { get; set; }
        public virtual DbSet<ProviderDiffResult> ProviderDiffResults { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<RuleStatu> RuleStatus { get; set; }
        public virtual DbSet<SpellFilter> SpellFilters { get; set; }
        public virtual DbSet<SpellIgnore> SpellIgnores { get; set; }
        public virtual DbSet<surface> surfaces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<TextTruncationRuleFilter> TextTruncationRuleFilters { get; set; }
        public virtual DbSet<UIContent> UIContents { get; set; }
        public virtual DbSet<UITrace> UITraces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VSOServer> VSOServers { get; set; }
        public virtual DbSet<WordsSharedWithEnglish> WordsSharedWithEnglishes { get; set; }
        public virtual DbSet<ControlTruncationRuleChildAndParentFilter> ControlTruncationRuleChildAndParentFilters { get; set; }
        public virtual DbSet<DeletedAssemblyLink> DeletedAssemblyLinks { get; set; }
        public virtual DbSet<FilterSpellCheck> FilterSpellChecks { get; set; }
        public virtual DbSet<FilterSpellingCheck> FilterSpellingChecks { get; set; }
        public virtual DbSet<NonEnglishButtonName> NonEnglishButtonNames { get; set; }
        public virtual DbSet<OverlapRuleChildAndParentFilter> OverlapRuleChildAndParentFilters { get; set; }
        public virtual DbSet<ResultsBack> ResultsBacks { get; set; }
        public virtual DbSet<temp_bug_surface> temp_bug_surface { get; set; }
        public virtual DbSet<temp_bugs> temp_bugs { get; set; }
        public virtual DbSet<VerticalSortPageNameList> VerticalSortPageNameLists { get; set; }
    }
}
