//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSpellCheck
    {
        public int id { get; set; }
        public string regexString { get; set; }
        public string properNoun { get; set; }
        public string nonEnglishButtonName { get; set; }
        public string pageExceptionType { get; set; }
        public string exceptionPageTitle { get; set; }
        public string excludeTextDetectPageTitle { get; set; }
        public string normalPunctuation { get; set; }
        public string reserve2 { get; set; }
        public string reserve3 { get; set; }
        public string reserve4 { get; set; }
    }
}
