//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_Cache
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LCX_Cache()
        {
            this.LCX_MainReport = new HashSet<LCX_MainReport>();
        }
    
        public int ID { get; set; }
        public string CompareBuilds { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool DetailGenerateStatus { get; set; }
        public bool MainReportGenerateStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCX_MainReport> LCX_MainReport { get; set; }
    }
}
