//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.SulpHur.CMRules
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SulpHurEntitiesForCMRules : DbContext
    {
        public SulpHurEntitiesForCMRules()
            : base("name=SulpHurEntitiesForCMRules")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FilterSpellCheck> FilterSpellChecks { get; set; }
        public virtual DbSet<VerticalSortPageNameList> VerticalSortPageNameLists { get; set; }
        public virtual DbSet<FilterSpellCheck_exceptionPageTitle> FilterSpellCheck_exceptionPageTitle { get; set; }
        public virtual DbSet<FilterSpellCheck_excludeTextDetectPageTitle> FilterSpellCheck_excludeTextDetectPageTitle { get; set; }
        public virtual DbSet<FilterSpellCheck_nonEnglishButtonName> FilterSpellCheck_nonEnglishButtonName { get; set; }
        public virtual DbSet<FilterSpellCheck_normalPunctuation> FilterSpellCheck_normalPunctuation { get; set; }
        public virtual DbSet<FilterSpellCheck_pageExceptionType> FilterSpellCheck_pageExceptionType { get; set; }
        public virtual DbSet<FilterSpellCheck_properNoun> FilterSpellCheck_properNoun { get; set; }
        public virtual DbSet<FilterSpellCheck_regexString> FilterSpellCheck_regexString { get; set; }
        public virtual DbSet<FilterSpellCheck_abnormalButNoImpact> FilterSpellCheck_abnormalButNoImpact { get; set; }
        public virtual DbSet<NonEnglishWordsButEnglishLetter> NonEnglishWordsButEnglishLetters { get; set; }
        public virtual DbSet<NonEnglishButtonName> NonEnglishButtonNames { get; set; }
        public virtual DbSet<WordsSharedWithEnglish> WordsSharedWithEnglishes { get; set; }
    }
}
