//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SH_People
    {
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Office { get; set; }
        public string Telephone { get; set; }
        public string OrgPath { get; set; }
        public string ImageLink { get; set; }
        public string AliasDomain { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> ID { get; set; }
        public string Mail { get; set; }
        public string UserPrincipalName { get; set; }
        public string TeamsUserID { get; set; }
        public string TeamsConversationID { get; set; }
        public string Avatars { get; set; }
    }
}
