//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_surface
    {
        public Nullable<int> s_id { get; set; }
        public Nullable<int> bug_id { get; set; }
        public int sb_id { get; set; }
    
        public virtual bug bug { get; set; }
        public virtual surface surface { get; set; }
    }
}
