//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_MainReport
    {
        public int ID { get; set; }
        public int CompareBuildID { get; set; }
        public int AssemblyID { get; set; }
        public int AssemblyFileStatus { get; set; }
        public string Resid_Full { get; set; }
        public string Resid { get; set; }
        public string Value_Old { get; set; }
        public string Value_New { get; set; }
        public bool ReferencedOnUI { get; set; }
        public string CHSValue_Old { get; set; }
        public string CHSValue_New { get; set; }
        public string CHS_ResultID { get; set; }
        public bool CHS_ManuallyVerified { get; set; }
        public string CHTValue_Old { get; set; }
        public string CHTValue_New { get; set; }
        public string CHT_ResultID { get; set; }
        public bool CHT_ManuallyVerified { get; set; }
        public string CSYValue_Old { get; set; }
        public string CSYValue_New { get; set; }
        public string CSY_ResultID { get; set; }
        public bool CSY_ManuallyVerified { get; set; }
        public string DANValue_Old { get; set; }
        public string DANValue_New { get; set; }
        public string DAN_ResultID { get; set; }
        public bool DAN_ManuallyVerified { get; set; }
        public string DEUValue_Old { get; set; }
        public string DEUValue_New { get; set; }
        public string DEU_ResultID { get; set; }
        public bool DEU_ManuallyVerified { get; set; }
        public string ELLValue_Old { get; set; }
        public string ELLValue_New { get; set; }
        public string ELL_ResultID { get; set; }
        public bool ELL_ManuallyVerified { get; set; }
        public string ENUValue_Old { get; set; }
        public string ENUValue_New { get; set; }
        public string ENU_ResultID { get; set; }
        public bool ENU_ManuallyVerified { get; set; }
        public string ESNValue_Old { get; set; }
        public string ESNValue_New { get; set; }
        public string ESN_ResultID { get; set; }
        public bool ESN_ManuallyVerified { get; set; }
        public string FINValue_Old { get; set; }
        public string FINValue_New { get; set; }
        public string FIN_ResultID { get; set; }
        public bool FIN_ManuallyVerified { get; set; }
        public string FRAValue_Old { get; set; }
        public string FRAValue_New { get; set; }
        public string FRA_ResultID { get; set; }
        public bool FRA_ManuallyVerified { get; set; }
        public string HUNValue_Old { get; set; }
        public string HUNValue_New { get; set; }
        public string HUN_ResultID { get; set; }
        public bool HUN_ManuallyVerified { get; set; }
        public string ITAValue_Old { get; set; }
        public string ITAValue_New { get; set; }
        public string ITA_ResultID { get; set; }
        public bool ITA_ManuallyVerified { get; set; }
        public string JPNValue_Old { get; set; }
        public string JPNValue_New { get; set; }
        public string JPN_ResultID { get; set; }
        public bool JPN_ManuallyVerified { get; set; }
        public string KORValue_Old { get; set; }
        public string KORValue_New { get; set; }
        public string KOR_ResultID { get; set; }
        public bool KOR_ManuallyVerified { get; set; }
        public string NLDValue_Old { get; set; }
        public string NLDValue_New { get; set; }
        public string NLD_ResultID { get; set; }
        public bool NLD_ManuallyVerified { get; set; }
        public string NORValue_Old { get; set; }
        public string NORValue_New { get; set; }
        public string NOR_ResultID { get; set; }
        public bool NOR_ManuallyVerified { get; set; }
        public string PLKValue_Old { get; set; }
        public string PLKValue_New { get; set; }
        public string PLK_ResultID { get; set; }
        public bool PLK_ManuallyVerified { get; set; }
        public string PTBValue_Old { get; set; }
        public string PTBValue_New { get; set; }
        public string PTB_ResultID { get; set; }
        public bool PTB_ManuallyVerified { get; set; }
        public string PTGValue_Old { get; set; }
        public string PTGValue_New { get; set; }
        public string PTG_ResultID { get; set; }
        public bool PTG_ManuallyVerified { get; set; }
        public string RUSValue_Old { get; set; }
        public string RUSValue_New { get; set; }
        public string RUS_ResultID { get; set; }
        public bool RUS_ManuallyVerified { get; set; }
        public string SVEValue_Old { get; set; }
        public string SVEValue_New { get; set; }
        public string SVE_ResultID { get; set; }
        public bool SVE_ManuallyVerified { get; set; }
        public string TRKValue_Old { get; set; }
        public string TRKValue_New { get; set; }
        public string TRK_ResultID { get; set; }
        public bool TRK_ManuallyVerified { get; set; }
    
        public virtual LCX_Assemblies LCX_Assemblies { get; set; }
        public virtual LCX_Cache LCX_Cache { get; set; }
    }
}
