//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_CacheLanguage
    {
        public int ID { get; set; }
        public string LanguageKey { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Status { get; set; }
    }
}
