//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogException
    {
        public int LogID { get; set; }
        public int ClientID { get; set; }
        public int BuildID { get; set; }
        public string ExceptionContent { get; set; }
        public System.DateTime InsertTime { get; set; }
        public System.DateTime LastModifyTime { get; set; }
        public int ExceptionCount { get; set; }
        public string Accessories { get; set; }
    
        public virtual BuildInfo BuildInfo { get; set; }
        public virtual Client Client { get; set; }
    }
}
