//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.SulpHur.SulpHurClient.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MS.Internal.SulpHur.SulpHurClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SulpHur Client 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 BuildType 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_BuildType {
            get {
                return ResourceManager.GetString("TrayMenu_BuildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Foreground Window 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_CaptureForegroundWnd {
            get {
                return ResourceManager.GetString("TrayMenu_CaptureForegroundWnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_Close {
            get {
                return ResourceManager.GetString("TrayMenu_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Sulphur Service 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_ConnectSulphur {
            get {
                return ResourceManager.GetString("TrayMenu_ConnectSulphur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_Mode {
            get {
                return ResourceManager.GetString("TrayMenu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show UI 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_ShowUI {
            get {
                return ResourceManager.GetString("TrayMenu_ShowUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn On/Off 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_TurnOnOff {
            get {
                return ResourceManager.GetString("TrayMenu_TurnOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Cached Data 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_UploadCachedData {
            get {
                return ResourceManager.GetString("TrayMenu_UploadCachedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Log 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_ViewLog {
            get {
                return ResourceManager.GetString("TrayMenu_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Report 的本地化字符串。
        /// </summary>
        internal static string TrayMenu_ViewReport {
            get {
                return ResourceManager.GetString("TrayMenu_ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SulpHur Client is already running. 的本地化字符串。
        /// </summary>
        internal static string TrayMessage_AlreadyRun {
            get {
                return ResourceManager.GetString("TrayMessage_AlreadyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SulpHur Client has connected to {0}! 的本地化字符串。
        /// </summary>
        internal static string TrayMessage_Connected {
            get {
                return ResourceManager.GetString("TrayMessage_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SulpHur Client fail to connect with {0}! 的本地化字符串。
        /// </summary>
        internal static string TrayMessage_ConnectFailed {
            get {
                return ResourceManager.GetString("TrayMessage_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automation 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_Automation {
            get {
                return ResourceManager.GetString("TraySubMenu_Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GenerateClass 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_GenerateClass {
            get {
                return ResourceManager.GetString("TraySubMenu_GenerateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_Main {
            get {
                return ResourceManager.GetString("TraySubMenu_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_Manual {
            get {
                return ResourceManager.GetString("TraySubMenu_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_Private {
            get {
                return ResourceManager.GetString("TraySubMenu_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_TurnOff {
            get {
                return ResourceManager.GetString("TraySubMenu_TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_TurnOn {
            get {
                return ResourceManager.GetString("TraySubMenu_TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI-Auto 的本地化字符串。
        /// </summary>
        internal static string TraySubMenu_UIAuto {
            get {
                return ResourceManager.GetString("TraySubMenu_UIAuto", resourceCulture);
            }
        }
    }
}
