//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bug()
        {
            this.bug_surface = new HashSet<bug_surface>();
        }
    
        public int bug_id { get; set; }
        public short status { get; set; }
        public string title { get; set; }
        public string repro { get; set; }
        public string assigned_to { get; set; }
        public Nullable<short> priority { get; set; }
        public Nullable<short> severity { get; set; }
        public string issue_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bug_surface> bug_surface { get; set; }
    }
}
