//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugLink
    {
        public int BugLinkID { get; set; }
        public int ContentID { get; set; }
        public int BugID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    
        public virtual UIContent UIContent { get; set; }
    }
}
