//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildVersionMap
    {
        public int BuildVersionMapID { get; set; }
        public string NewFormatBuildVersion { get; set; }
        public string StandardFormatBuildVersion { get; set; }
    }
}
