//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildType
    {
        public int RecordID { get; set; }
        public string AssemblyName { get; set; }
        public string TypeName { get; set; }
        public string BuildNo { get; set; }
        public string Mark { get; set; }
        public string LanuchSteps { get; set; }
    }
}
