//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_Details
    {
        public int ID { get; set; }
        public int LanguageKeyID { get; set; }
        public int AssemblyID { get; set; }
        public int FileStatus { get; set; }
        public string Resid_Full { get; set; }
        public string Resid { get; set; }
        public string EnuBefore { get; set; }
        public string EnuAfter { get; set; }
        public int EnuAfterWC { get; set; }
        public int EnuStringIs { get; set; }
        public string LocBefore { get; set; }
        public string LocAfter { get; set; }
        public int LocAfterWC { get; set; }
        public int LocStringIs { get; set; }
        public string LocStatusBefore { get; set; }
        public string LocStatusAfter { get; set; }
        public bool IsEmptyString { get; set; }
    }
}
