//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_Assemblies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LCX_Assemblies()
        {
            this.LCX_AssociationAssembly = new HashSet<LCX_AssociationAssembly>();
            this.LCX_AssociationAssembly1 = new HashSet<LCX_AssociationAssembly>();
            this.LCX_MainReport = new HashSet<LCX_MainReport>();
        }
    
        public int ID { get; set; }
        public string Assembly { get; set; }
        public bool Trace { get; set; }
        public bool IsGeneral { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public Nullable<int> OwnerID { get; set; }
    
        public virtual LCX_Employers LCX_Employers { get; set; }
        public virtual LCX_Features LCX_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCX_AssociationAssembly> LCX_AssociationAssembly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCX_AssociationAssembly> LCX_AssociationAssembly1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LCX_MainReport> LCX_MainReport { get; set; }
    }
}
