//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCX_StringDetails
    {
        public int ID { get; set; }
        public int BuildID { get; set; }
        public string Language { get; set; }
        public string FileName { get; set; }
        public string ResID_Full { get; set; }
        public string ResID { get; set; }
        public string Value { get; set; }
    
        public virtual LCX_StringBuilds LCX_StringBuilds { get; set; }
    }
}
