//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverlapRuleFilter
    {
        public int OverlapRuleFilterID { get; set; }
        public string RootAutomationID { get; set; }
        public string FirstControlAutomationID { get; set; }
        public string FirstControlType { get; set; }
        public string SecondControlAutomationID { get; set; }
        public string SecondControlType { get; set; }
    }
}
