//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderDiffResult
    {
        public int ResultID { get; set; }
        public string DiffType { get; set; }
        public string WmiClassName { get; set; }
        public string WmiClassBody { get; set; }
        public string SourceFileName { get; set; }
        public Nullable<int> ContentIDPre { get; set; }
        public Nullable<int> ContentIDPost { get; set; }
        public string AssemblyName { get; set; }
        public Nullable<bool> HasImage { get; set; }
        public string PageName { get; set; }
        public string ComparedBuild { get; set; }
        public string OldClass { get; set; }
        public string NewClass { get; set; }
    }
}
