//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsInfoByAlia
    {
        public int ResultID { get; set; }
        public string buildNo { get; set; }
        public string Language { get; set; }
        public string RuleName { get; set; }
        public string ResultType { get; set; }
        public string UIName { get; set; }
        public string UserName { get; set; }
        public string OSType { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ReviewFlag { get; set; }
        public string alias { get; set; }
    }
}
