//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpellIgnore
    {
        public int SpellIgnoreID { get; set; }
        public string ENUStr { get; set; }
        public string CHSStr { get; set; }
        public string DEUStr { get; set; }
        public string FRAStr { get; set; }
        public string JPNStr { get; set; }
        public string RUSStr { get; set; }
        public string CHTStr { get; set; }
        public string CSYStr { get; set; }
        public string ESNStr { get; set; }
        public string HUNStr { get; set; }
        public string ITAStr { get; set; }
        public string KORStr { get; set; }
        public string NLDStr { get; set; }
        public string PLKStr { get; set; }
        public string PTBStr { get; set; }
        public string PTGStr { get; set; }
        public string SVEStr { get; set; }
        public string TRKStr { get; set; }
        public string DANStr { get; set; }
        public string ELLStr { get; set; }
        public string FINStr { get; set; }
        public string NORStr { get; set; }
    }
}
