//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIContent()
        {
            this.AssemblyLinks = new HashSet<AssemblyLink>();
            this.BugLinks = new HashSet<BugLink>();
            this.Results = new HashSet<Result>();
            this.RuleStatus = new HashSet<RuleStatu>();
        }
    
        public int ContentID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public int ClientID { get; set; }
        public int BuildID { get; set; }
        public string UIName { get; set; }
        public string UIContent1 { get; set; }
        public byte[] UIScreenShot { get; set; }
        public bool IsWebUI { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public Nullable<int> TraceID { get; set; }
        public Nullable<int> Reserve1 { get; set; }
        public string Reserve2 { get; set; }
        public string Reserve3 { get; set; }
        public string Reserve4 { get; set; }
        public string Reserve5 { get; set; }
        public string LaunchedFrom { get; set; }
        public string WindowHierarchy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyLink> AssemblyLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BugLink> BugLinks { get; set; }
        public virtual BuildInfo BuildInfo { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleStatu> RuleStatus { get; set; }
    }
}
