//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MogenDebug
{
    using System;
    using System.Collections.Generic;
    
    public partial class UITrace
    {
        public int TraceID { get; set; }
        public string TraceName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> Reserve1 { get; set; }
        public string Reserve2 { get; set; }
    }
}
