//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.SulpHur.CMRules
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterSpellCheck_abnormalButNoImpact
    {
        public int ID { get; set; }
        public int abnormalButNoImpact { get; set; }
    }
}
