//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.SulpHur.CMRules
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextTruncationRuleFilter
    {
        public int TextTruncationRuleFilterID { get; set; }
        public string RootAutomationID { get; set; }
        public string ControlAutomationID { get; set; }
        public string ControlType { get; set; }
    }
}
