//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MS.Internal.SulpHur.CMRules
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordsSharedWithEnglish
    {
        public int id { get; set; }
        public string Word { get; set; }
        public bool ENU { get; set; }
        public bool CHS { get; set; }
        public bool DEU { get; set; }
        public bool FRA { get; set; }
        public bool JPN { get; set; }
        public bool RUS { get; set; }
        public bool CHT { get; set; }
        public bool CSY { get; set; }
        public bool ESN { get; set; }
        public bool HUN { get; set; }
        public bool ITA { get; set; }
        public bool KOR { get; set; }
        public bool NLD { get; set; }
        public bool PLK { get; set; }
        public bool PTB { get; set; }
        public bool PTG { get; set; }
        public bool SVE { get; set; }
        public bool TRK { get; set; }
        public bool DAN { get; set; }
        public bool ELL { get; set; }
        public bool FIN { get; set; }
        public bool NOR { get; set; }
    }
}
