//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDOMSample
{
    using System;
    
    
    public partial class CodeDOMCreatedClass
    {
        
        // The width of the object.
        private double widthValue;
        
        // The height of the object.
        private double heightValue;
        
        public CodeDOMCreatedClass(double width, double height)
        {
            this.widthValue = width;
            this.heightValue = height;
        }
        
        // The Width property for the object.
        public double Width
        {
            get
            {
                return this.widthValue;
            }
        }
        
        // The Height property for the object.
        public double Height
        {
            get
            {
                return this.heightValue;
            }
        }
        
        // The Area property for the object.
        public double Area
        {
            get
            {
                return (this.widthValue * this.heightValue);
            }
        }
        
        public override string ToString()
        {
            return string.Format("The object:\r\n width = {0},\r\n height = {1},\r\n area = {2}", this.Width, this.Height, this.Area);
        }
        
        public static void Main()
        {
            CodeDOMCreatedClass testClass = new CodeDOMCreatedClass(5.3D, 6.9D);
            System.Console.WriteLine(testClass.ToString());
        }
    }
}
