//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulpHurReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rule()
        {
            this.Results = new HashSet<Result>();
            this.RuleStatus = new HashSet<RuleStatu>();
        }
    
        public int RuleID { get; set; }
        public string RuleName { get; set; }
        public string RulePath { get; set; }
        public string RuleDesc { get; set; }
        public bool IsEnabled { get; set; }
        public string AssemblyInfo { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> IsObsoluted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleStatu> RuleStatus { get; set; }
    }
}
